// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJJ8MCHye9sDOZDNmFMGR6V-__jgNZazQ',
    appId: '1:561388224593:web:fb89cba2155d97b5c9b870',
    messagingSenderId: '561388224593',
    projectId: 'aienergon',
    authDomain: 'aienergon.firebaseapp.com',
    storageBucket: 'aienergon.firebasestorage.app',
    measurementId: 'G-3RP8KXHMZ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6PjPKLO2yiM2K4PoP1c7eev6ITt9dvGc',
    appId: '1:561388224593:android:82508cecfae9c30fc9b870',
    messagingSenderId: '561388224593',
    projectId: 'aienergon',
    storageBucket: 'aienergon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwPjiF18Clq-LpQW-i907OJlsunzCd3s8',
    appId: '1:561388224593:ios:7e8bebfaea2ab8efc9b870',
    messagingSenderId: '561388224593',
    projectId: 'aienergon',
    storageBucket: 'aienergon.firebasestorage.app',
    iosBundleId: 'com.example.carManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwPjiF18Clq-LpQW-i907OJlsunzCd3s8',
    appId: '1:561388224593:ios:7e8bebfaea2ab8efc9b870',
    messagingSenderId: '561388224593',
    projectId: 'aienergon',
    storageBucket: 'aienergon.firebasestorage.app',
    iosBundleId: 'com.example.carManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJJ8MCHye9sDOZDNmFMGR6V-__jgNZazQ',
    appId: '1:561388224593:web:96730c8a092cb54cc9b870',
    messagingSenderId: '561388224593',
    projectId: 'aienergon',
    authDomain: 'aienergon.firebaseapp.com',
    storageBucket: 'aienergon.firebasestorage.app',
    measurementId: 'G-K0QJ2PX28G',
  );
}
